import type { Metadata, Viewport } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "@/stack/client";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import ConditionalSiteChrome from "@/components/layout/ConditionalSiteChrome";
import HolyLoader from "holy-loader";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Shopco",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <StackProvider app={stackClientApp}>
          <StackTheme>
            <HolyLoader color="#868686" />
            <Providers>
              <ConditionalSiteChrome>{children}</ConditionalSiteChrome>
            </Providers>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
